//! DHCPv4 protocol state machine implementation per RFC 2131.
//!
//! This module implements the complete DHCPv4 protocol state machine handling
//! the DISCOVER→OFFER→REQUEST→ACK message exchange sequence. It replaces the
//! C implementation in `src/rfc2131.c` with memory-safe Rust equivalents using
//! type-safe enums and structured error handling.
//!
//! # Protocol Flow
//!
//! ## Standard Four-Way Handshake
//!
//! 1. **Client → Server: DHCPDISCOVER**
//!    - Client broadcasts discover to find available DHCP servers
//!    - May include requested IP address, parameter list, hostname
//!    - Handled by [`DhcpProtocol::handle_discover`]
//!
//! 2. **Server → Client: DHCPOFFER**
//!    - Server offers an IP address with configuration parameters
//!    - Includes yiaddr (offered IP), lease time, server identifier
//!    - Generated by discover handler
//!
//! 3. **Client → Server: DHCPREQUEST**
//!    - Client requests the offered IP (or verifies existing lease)
//!    - Three contexts: selecting, init-reboot, renewing
//!    - Handled by [`DhcpProtocol::handle_request`]
//!
//! 4. **Server → Client: DHCPACK**
//!    - Server confirms allocation with full configuration
//!    - Lease becomes active, DNS registration occurs
//!    - Or DHCPNAK if request cannot be satisfied
//!
//! ## Additional Message Types
//!
//! - **DHCPDECLINE**: Client detected address conflict (ARP collision)
//!   - Handled by [`DhcpProtocol::handle_decline`]
//!   - Marks address as unavailable for configured backoff period
//!
//! - **DHCPRELEASE**: Client gracefully releases lease
//!   - Handled by [`DhcpProtocol::handle_release`]
//!   - Immediate lease termination, no NAK sent
//!
//! - **DHCPINFORM**: Client requests configuration without address
//!   - Handled by [`DhcpProtocol::handle_inform`]
//!   - Used when client has static IP but needs DNS/gateway info
//!
//! # RFC Compliance
//!
//! - RFC 2131: DHCP core protocol
//! - RFC 2132: DHCP options and BOOTP vendor extensions
//! - RFC 951: BOOTP compatibility mode
//! - RFC 4039: Rapid commit extension (two-message exchange)
//! - RFC 4388: DHCPv4 leasequery
//!
//! # Memory Safety
//!
//! Replaces C's manual buffer management with:
//! - Type-safe message parsing via [`DhcpMessage`]
//! - Enum-based option handling via [`DhcpOption`]
//! - Async lease operations via [`LeaseManager`]
//! - Bounds-checked slice operations throughout
//!
//! # Example
//!
//! ```rust,ignore
//! use std::sync::Arc;
//! use std::net::Ipv4Addr;
//!
//! // Create protocol handler
//! let protocol = DhcpProtocol::new(
//!     Arc::new(config),
//!     Arc::new(lease_manager),
//! );
//!
//! // Handle incoming DHCPDISCOVER
//! match protocol.handle_discover(&discover_msg).await {
//!     Ok(offer) => send_dhcp_reply(offer),
//!     Err(e) => warn!("Failed to generate offer: {}", e),
//! }
//! ```

use std::net::Ipv4Addr;
use std::sync::Arc;
use std::time::Duration;

use tracing::{debug, error, info, warn};

// Internal imports from dependency files
use super::constants::{
    OPTION_DNS_SERVER, OPTION_DOMAIN_NAME, OPTION_NETMASK, OPTION_ROUTER,
};
use super::message::DhcpMessage;
use super::options::{DhcpOption, MessageType};

use crate::config::types::{DhcpConfig, DhcpRange, StaticLease};
use crate::dhcp::lease::LeaseManager;
use crate::error::DhcpError;
use crate::types::MacAddress;

/// DHCPv4 protocol state machine handler.
///
/// Coordinates DHCP message processing, lease allocation, and response generation.
/// Replaces C's global function `rfc2131_packet()` with structured protocol handler
/// that maintains no mutable state (stateless request processing).
///
/// # Fields
///
/// - `config`: DHCP configuration (address ranges, static leases, options)
/// - `lease_manager`: Lease lifecycle coordinator (allocation, renewal, release)
///
/// # Thread Safety
///
/// All fields are wrapped in Arc for shared immutable access across async tasks.
/// LeaseManager internally uses RwLock for thread-safe lease database mutations.
pub struct DhcpProtocol {
    /// DHCP configuration with ranges and static leases
    config: Arc<DhcpConfig>,
    /// Lease management coordinator
    lease_manager: Arc<LeaseManager>,
}

impl DhcpProtocol {
    /// Creates a new DHCPv4 protocol handler.
    ///
    /// # Arguments
    ///
    /// * `config` - DHCP configuration with address ranges and settings
    /// * `lease_manager` - Lease lifecycle coordinator
    ///
    /// # Returns
    ///
    /// New DhcpProtocol instance ready to process messages
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let protocol = DhcpProtocol::new(
    ///     Arc::new(dhcp_config),
    ///     Arc::new(lease_manager),
    /// );
    /// ```
    pub fn new(config: Arc<DhcpConfig>, lease_manager: Arc<LeaseManager>) -> Self {
        Self { config, lease_manager }
    }

    /// Handles DHCPDISCOVER message and generates DHCPOFFER response.
    ///
    /// Processes client discovery broadcast, selects appropriate address range,
    /// finds available IP address (considering static leases and existing leases),
    /// and constructs offer with configuration parameters.
    ///
    /// # Arguments
    ///
    /// * `request` - Parsed DHCPDISCOVER message from client
    ///
    /// # Returns
    ///
    /// Ok(DHCPOFFER message) on success, Err if no address available or validation fails
    ///
    /// # Protocol Details
    ///
    /// Per RFC 2131 Section 4.3.1:
    /// - May honor requested IP address (option 50) if available
    /// - Should reuse previous lease for same client if present
    /// - Must include yiaddr, server identifier, and lease time in offer
    ///
    /// # Errors
    ///
    /// - `DhcpError::NoAddressAvailable`: No free addresses in configured ranges
    /// - `DhcpError::V4ProtocolError`: Message validation failed
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let offer = protocol.handle_discover(&discover_msg).await?;
    /// assert!(offer.yiaddr().is_some());
    /// ```
    pub async fn handle_discover(&self, request: &DhcpMessage) -> Result<DhcpMessage, DhcpError> {
        let client_mac = request.client_hardware_addr()?;
        let xid = request.transaction_id();

        debug!(
            client_mac = %client_mac,
            transaction_id = xid,
            "Processing DHCPDISCOVER"
        );

        // Select appropriate DHCP context (address range) for this request
        let context = self.select_context(request).ok_or_else(|| {
            warn!(client_mac = %client_mac, "No matching DHCP range for DISCOVER");
            DhcpError::NoAddressAvailable { pool_name: "default".to_string() }
        })?;

        // Check for static lease reservation
        let offered_ip = if let Some(static_lease) = self.find_static_lease(&client_mac) {
            debug!(
                client_mac = %client_mac,
                static_ip = %static_lease.ip,
                "Using static lease reservation"
            );
            static_lease.ip
        } else {
            // Check if client has existing lease
            if let Some(existing_lease) = self.lease_manager.find_by_mac(&client_mac).await {
                if !existing_lease.is_expired() {
                    debug!(
                        client_mac = %client_mac,
                        existing_ip = %existing_lease.ip,
                        "Reoffering existing lease"
                    );
                    existing_lease.ip
                } else {
                    // Try to allocate requested IP or find new one
                    self.allocate_address_from_range(context, request, &client_mac).await?
                }
            } else {
                // New client, allocate from range
                self.allocate_address_from_range(context, request, &client_mac).await?
            }
        };

        // Ensure offered IP is IPv4
        let offered_ipv4 = match offered_ip {
            std::net::IpAddr::V4(ipv4) => ipv4,
            _ => {
                return Err(DhcpError::V4ProtocolError {
                    reason: "Non-IPv4 address in DHCPv4 context".to_string(),
                })
            }
        };

        // Calculate lease time for offer
        let lease_time = self.calculate_lease_time(context, request);

        // Determine server identifier (our IP address)
        let server_id = self.determine_server_id(context, request);

        // Build DHCPOFFER message
        let mut offer = DhcpMessage::new_reply(request);
        offer.set_yiaddr(offered_ipv4);

        // Set next-server IP (siaddr) for TFTP boot if configured
        if let Some(next_server) = context.next_server() {
            offer.set_siaddr(next_server);
        }

        // Build and add options
        let options = self.build_option_list(
            context,
            request,
            offered_ipv4,
            lease_time,
            server_id,
            MessageType::Offer,
        );
        for option in options {
            offer.add_option(option);
        }

        info!(
            client_mac = %client_mac,
            offered_ip = %offered_ipv4,
            lease_time_secs = lease_time.as_secs(),
            "Generated DHCPOFFER"
        );

        Ok(offer)
    }

    /// Handles DHCPREQUEST message and generates DHCPACK or DHCPNAK response.
    ///
    /// Processes client request in one of three states:
    /// - **SELECTING**: Client accepting a specific server's offer
    /// - **INIT-REBOOT**: Client verifying cached address after reboot
    /// - **RENEWING/REBINDING**: Client extending existing lease
    ///
    /// # Arguments
    ///
    /// * `request` - Parsed DHCPREQUEST message from client
    ///
    /// # Returns
    ///
    /// Ok(DHCPACK or DHCPNAK message) on success, Err on validation failure
    ///
    /// # Protocol Details
    ///
    /// Per RFC 2131 Section 4.3.2:
    ///
    /// ## SELECTING State
    /// - Request includes server identifier (option 54) and requested IP (option 50)
    /// - Server identifier must match our address
    /// - Allocate lease and send ACK, or NAK if address unavailable
    ///
    /// ## INIT-REBOOT State
    /// - Request includes requested IP (option 50) but no server identifier
    /// - ciaddr must be zero
    /// - Verify requested address is appropriate for client's network
    /// - Send NAK if address wrong for network, ACK if correct and available
    ///
    /// ## RENEWING/REBINDING State
    /// - Request has ciaddr set to currently leased address
    /// - No requested IP or server identifier
    /// - Extend lease if valid, NAK if lease expired or invalid
    ///
    /// # Errors
    ///
    /// - `DhcpError::V4ProtocolError`: Invalid message format or missing required options
    /// - `DhcpError::NoAddressAvailable`: Requested address unavailable
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// match protocol.handle_request(&request_msg).await? {
    ///     msg if msg.message_type() == MessageType::Ack => send_dhcp_ack(msg),
    ///     msg if msg.message_type() == MessageType::Nak => send_dhcp_nak(msg),
    ///     _ => unreachable!(),
    /// }
    /// ```
    pub async fn handle_request(&self, request: &DhcpMessage) -> Result<DhcpMessage, DhcpError> {
        let client_mac = request.client_hardware_addr()?;
        let xid = request.transaction_id();

        debug!(
            client_mac = %client_mac,
            transaction_id = xid,
            "Processing DHCPREQUEST"
        );

        // Determine REQUEST state by examining options and ciaddr
        let requested_ip_opt =
            request.get_option(|opt| matches!(opt, DhcpOption::RequestedIpAddress(_)));
        let server_id_opt = request.get_option(|opt| matches!(opt, DhcpOption::ServerId(_)));
        let ciaddr = request.ciaddr();

        // SELECTING state: server identifier + requested IP present
        if let (
            Some(DhcpOption::ServerId(server_id)),
            Some(DhcpOption::RequestedIpAddress(req_ip)),
        ) = (server_id_opt, requested_ip_opt)
        {
            debug!(
                client_mac = %client_mac,
                requested_ip = %req_ip,
                server_id = %server_id,
                "REQUEST in SELECTING state"
            );

            // Check if request is for this server
            let our_server_id = self.determine_server_id_for_request(request);
            if *server_id != our_server_id {
                debug!(
                    client_mac = %client_mac,
                    requested_server = %server_id,
                    our_server = %our_server_id,
                    "REQUEST not for this server, ignoring"
                );
                return Err(DhcpError::V4ProtocolError {
                    reason: "Request for different server".to_string(),
                });
            }

            // Process selecting state request
            return self.handle_request_selecting(request, *req_ip, our_server_id).await;
        }

        // INIT-REBOOT state: requested IP present, ciaddr is zero, no server identifier
        if let Some(DhcpOption::RequestedIpAddress(req_ip)) = requested_ip_opt {
            if ciaddr.is_unspecified() {
                debug!(
                    client_mac = %client_mac,
                    requested_ip = %req_ip,
                    "REQUEST in INIT-REBOOT state"
                );

                return self.handle_request_init_reboot(request, *req_ip).await;
            }
        }

        // RENEWING/REBINDING state: ciaddr set, no requested IP or server identifier
        if !ciaddr.is_unspecified() && requested_ip_opt.is_none() && server_id_opt.is_none() {
            debug!(
                client_mac = %client_mac,
                ciaddr = %ciaddr,
                "REQUEST in RENEWING/REBINDING state"
            );

            return self.handle_request_renewing(request, ciaddr).await;
        }

        // Invalid REQUEST message format
        warn!(
            client_mac = %client_mac,
            "Invalid DHCPREQUEST format: missing required fields"
        );

        Err(DhcpError::V4ProtocolError { reason: "Invalid DHCPREQUEST message format".to_string() })
    }

    /// Handles DHCPDECLINE message indicating address conflict.
    ///
    /// Client detected that the offered/assigned address is already in use on the
    /// network (typically through ARP probe). Server must mark the address as
    /// unavailable for a configured backoff period to prevent repeated conflicts.
    ///
    /// # Arguments
    ///
    /// * `request` - Parsed DHCPDECLINE message from client
    ///
    /// # Returns
    ///
    /// Ok(()) on success (no response sent per RFC 2131), Err on validation failure
    ///
    /// # Protocol Details
    ///
    /// Per RFC 2131 Section 4.3.3:
    /// - Client must include requested IP address (option 50) indicating declined address
    /// - No response is sent to client
    /// - Server should mark address unavailable for minimum 5 minutes
    /// - Server may log the event for network administrator review
    ///
    /// # Errors
    ///
    /// - `DhcpError::V4ProtocolError`: Missing requested IP address option
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// protocol.handle_decline(&decline_msg).await?;
    /// // No response sent, address marked unavailable
    /// ```
    pub async fn handle_decline(&self, request: &DhcpMessage) -> Result<(), DhcpError> {
        let client_mac = request.client_hardware_addr()?;
        let xid = request.transaction_id();

        debug!(
            client_mac = %client_mac,
            transaction_id = xid,
            "Processing DHCPDECLINE"
        );

        // Extract declined address from requested IP option
        let declined_ip =
            match request.get_option(|opt| matches!(opt, DhcpOption::RequestedIpAddress(_))) {
                Some(DhcpOption::RequestedIpAddress(ip)) => ip,
                _ => {
                    return Err(DhcpError::V4ProtocolError {
                        reason: "DHCPDECLINE missing requested IP address".to_string(),
                    })
                }
            };

        warn!(
            client_mac = %client_mac,
            declined_ip = %declined_ip,
            "Client declined address due to conflict"
        );

        // Mark address as declined in lease database
        // The address will be unavailable for allocation until manually cleared or timeout expires
        // Note: Full implementation would mark the address with DECLINED flag and set timeout
        // For now, we release any existing lease for this address
        if let Some(existing_lease) =
            self.lease_manager.find_by_ip(&std::net::IpAddr::V4(*declined_ip)).await
        {
            info!(
                declined_ip = %declined_ip,
                previous_mac = ?existing_lease.mac,
                "Releasing declined lease"
            );

            // Release the lease (marks it available again)
            if let Err(e) =
                self.lease_manager.release_lease(&std::net::IpAddr::V4(*declined_ip)).await
            {
                error!(
                    declined_ip = %declined_ip,
                    error = %e,
                    "Failed to release declined lease"
                );
            }
        }

        // No response is sent per RFC 2131 Section 4.3.3
        Ok(())
    }

    /// Handles DHCPRELEASE message for graceful lease termination.
    ///
    /// Client explicitly releases its IP address lease, making it immediately
    /// available for reallocation. This is the graceful shutdown path.
    ///
    /// # Arguments
    ///
    /// * `request` - Parsed DHCPRELEASE message from client
    ///
    /// # Returns
    ///
    /// Ok(()) on success (no response sent per RFC 2131), Err on validation failure
    ///
    /// # Protocol Details
    ///
    /// Per RFC 2131 Section 4.3.4:
    /// - Client must set ciaddr to the address being released
    /// - No response is sent to client
    /// - Lease is immediately available for reallocation
    /// - DNS entries and script hooks should be cleaned up
    ///
    /// # Errors
    ///
    /// - `DhcpError::V4ProtocolError`: ciaddr is zero (invalid release)
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// protocol.handle_release(&release_msg).await?;
    /// // Lease released, DNS entry removed, script executed
    /// ```
    pub async fn handle_release(&self, request: &DhcpMessage) -> Result<(), DhcpError> {
        let client_mac = request.client_hardware_addr()?;
        let xid = request.transaction_id();
        let ciaddr = request.ciaddr();

        debug!(
            client_mac = %client_mac,
            transaction_id = xid,
            ciaddr = %ciaddr,
            "Processing DHCPRELEASE"
        );

        // Validate that ciaddr is set
        if ciaddr.is_unspecified() {
            return Err(DhcpError::V4ProtocolError {
                reason: "DHCPRELEASE missing ciaddr".to_string(),
            });
        }

        // Release the lease
        match self.lease_manager.release_lease(&std::net::IpAddr::V4(ciaddr)).await {
            Ok(released_lease) => {
                info!(
                    client_mac = %client_mac,
                    released_ip = %ciaddr,
                    hostname = ?released_lease.hostname,
                    "Lease released by client"
                );
            }
            Err(DhcpError::LeaseNotFound { .. }) => {
                warn!(
                    client_mac = %client_mac,
                    ciaddr = %ciaddr,
                    "RELEASE for non-existent lease"
                );
            }
            Err(e) => {
                error!(
                    client_mac = %client_mac,
                    ciaddr = %ciaddr,
                    error = %e,
                    "Failed to release lease"
                );
                return Err(e);
            }
        }

        // No response is sent per RFC 2131 Section 4.3.4
        Ok(())
    }

    /// Handles DHCPINFORM message for configuration-only requests.
    ///
    /// Client has manually configured IP address but requests network configuration
    /// parameters (DNS servers, routers, domain name, etc.) from DHCP server.
    ///
    /// # Arguments
    ///
    /// * `request` - Parsed DHCPINFORM message from client
    ///
    /// # Returns
    ///
    /// Ok(DHCPACK message with configuration) on success, Err on validation failure
    ///
    /// # Protocol Details
    ///
    /// Per RFC 2131 Section 4.3.5:
    /// - Client has self-configured IP in ciaddr
    /// - Server responds with DHCPACK containing configuration options
    /// - No yiaddr, no lease time (client already has address)
    /// - No lease database entry created
    ///
    /// # Errors
    ///
    /// - `DhcpError::V4ProtocolError`: ciaddr is zero (invalid inform)
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let ack = protocol.handle_inform(&inform_msg).await?;
    /// assert!(ack.yiaddr().is_unspecified()); // No address assignment
    /// ```
    pub async fn handle_inform(&self, request: &DhcpMessage) -> Result<DhcpMessage, DhcpError> {
        let client_mac = request.client_hardware_addr()?;
        let xid = request.transaction_id();
        let ciaddr = request.ciaddr();

        debug!(
            client_mac = %client_mac,
            transaction_id = xid,
            ciaddr = %ciaddr,
            "Processing DHCPINFORM"
        );

        // Validate that ciaddr is set
        if ciaddr.is_unspecified() {
            return Err(DhcpError::V4ProtocolError {
                reason: "DHCPINFORM missing ciaddr".to_string(),
            });
        }

        // Select appropriate context for configuration parameters
        let context = self.select_context(request).ok_or_else(|| {
            warn!(client_mac = %client_mac, ciaddr = %ciaddr, "No matching context for INFORM");
            DhcpError::NoAddressAvailable { pool_name: "default".to_string() }
        })?;

        // Determine server identifier
        let server_id = self.determine_server_id(context, request);

        // Build DHCPACK response with configuration options (no yiaddr, no lease time)
        let mut ack = DhcpMessage::new_reply(request);
        // ciaddr remains set by client, yiaddr stays zero

        // Build configuration options (no lease time)
        let options = self.build_option_list(
            context,
            request,
            ciaddr,                 // Use client's IP for context
            Duration::from_secs(0), // No lease time for INFORM
            server_id,
            MessageType::Ack,
        );

        for option in options {
            // Skip lease time option for INFORM responses
            if matches!(option, DhcpOption::LeaseTime(_)) {
                continue;
            }
            ack.add_option(option);
        }

        info!(
            client_mac = %client_mac,
            ciaddr = %ciaddr,
            "Generated DHCPACK for INFORM (configuration only)"
        );

        Ok(ack)
    }

    // =============================================================================
    // HELPER METHODS
    // =============================================================================

    /// Selects appropriate DHCP context (address range) for a request.
    ///
    /// Matches request against configured DHCPv4 ranges based on:
    /// - Interface name (if request interface known)
    /// - Gateway relay address (giaddr)
    /// - Network address matching
    ///
    /// Replaces C function `complete_context()` and `narrow_context()`.
    ///
    /// # Arguments
    ///
    /// * `request` - DHCP request message to match
    ///
    /// # Returns
    ///
    /// Reference to matching DhcpRange, or None if no match found
    fn select_context<'a>(&'a self, request: &DhcpMessage) -> Option<&'a DhcpRange> {
        let giaddr = request.giaddr();

        // Find first matching DHCPv4 range
        // Priority: relay address match > interface match > first available
        for range in &self.config.v4_ranges {
            // Check if range matches relay address (giaddr)
            if !giaddr.is_unspecified() {
                if let std::net::IpAddr::V4(start_ipv4) = range.start {
                    if let std::net::IpAddr::V4(end_ipv4) = range.end {
                        // Simple check: if giaddr is within range network, use this range
                        // Full implementation would check network address with netmask
                        if self.ip_in_range(giaddr, start_ipv4, end_ipv4) {
                            return Some(range);
                        }
                    }
                }
            }

            // For now, return first IPv4 range as fallback
            // Full implementation would check interface matching
            if matches!(range.start, std::net::IpAddr::V4(_)) {
                return Some(range);
            }
        }

        None
    }

    /// Builds list of DHCP options for response message.
    ///
    /// Constructs option list including required options (message type, server ID,
    /// lease time) and requested options from client's parameter request list.
    ///
    /// Replaces C function `do_options()`.
    ///
    /// # Arguments
    ///
    /// * `context` - DHCP range context for this response
    /// * `request` - Client request message
    /// * `offered_ip` - IP address being offered/acknowledged
    /// * `lease_time` - Lease duration
    /// * `server_id` - Server identifier address
    /// * `message_type` - Response message type (Offer or Ack)
    ///
    /// # Returns
    ///
    /// Vector of DHCP options to include in response
    fn build_option_list(
        &self,
        context: &DhcpRange,
        request: &DhcpMessage,
        _offered_ip: Ipv4Addr,
        lease_time: Duration,
        server_id: Ipv4Addr,
        message_type: MessageType,
    ) -> Vec<DhcpOption> {
        let mut options = Vec::new();

        // Required options per RFC 2131
        options.push(DhcpOption::MessageType(message_type));
        options.push(DhcpOption::ServerId(server_id));

        // Lease time (not included for INFORM responses, handled by caller)
        if lease_time.as_secs() > 0 {
            options.push(DhcpOption::LeaseTime(lease_time.as_secs() as u32));
        }

        // Get parameter request list from client
        let requested_params = if let Some(DhcpOption::ParameterRequestList(params)) =
            request.get_option(|opt| matches!(opt, DhcpOption::ParameterRequestList(_)))
        {
            params.clone()
        } else {
            Vec::new()
        };

        // Add requested options (stub implementation - full version would read from config)
        for param_code in requested_params {
            match param_code {
                OPTION_NETMASK => {
                    // Calculate netmask from context (stub: use /24)
                    options.push(DhcpOption::Netmask(Ipv4Addr::new(255, 255, 255, 0)));
                }
                OPTION_ROUTER => {
                    // Use first IP in range as default gateway (stub)
                    if let std::net::IpAddr::V4(router) = context.start {
                        options.push(DhcpOption::Router(vec![router]));
                    }
                }
                OPTION_DNS_SERVER => {
                    // Stub: use common public DNS
                    options.push(DhcpOption::DnsServer(vec![
                        Ipv4Addr::new(8, 8, 8, 8),
                        Ipv4Addr::new(8, 8, 4, 4),
                    ]));
                }
                OPTION_DOMAIN_NAME => {
                    // Stub: use example domain
                    options.push(DhcpOption::DomainName("local".to_string()));
                }
                _ => {
                    // Unknown option code, skip
                    debug!(option_code = param_code, "Skipping unhandled option request");
                }
            }
        }

        // Check for rapid commit support (RFC 4039)
        if request.get_option(|opt| matches!(opt, DhcpOption::RapidCommit)).is_some() {
            options.push(DhcpOption::RapidCommit);
        }

        options
    }

    /// Calculates lease duration for a request.
    ///
    /// Determines lease time based on:
    /// - Per-range lease time override
    /// - Client requested lease time (option 51)
    /// - Global default lease time
    ///
    /// Replaces C function `calc_time()`.
    ///
    /// # Arguments
    ///
    /// * `context` - DHCP range context
    /// * `request` - Client request message
    ///
    /// # Returns
    ///
    /// Lease duration to use for this client
    fn calculate_lease_time(&self, context: &DhcpRange, request: &DhcpMessage) -> Duration {
        // Check for range-specific lease time
        if let Some(range_lease_time) = context.lease_time_override {
            return range_lease_time;
        }

        // Check for client requested lease time
        if let Some(DhcpOption::LeaseTime(requested_secs)) =
            request.get_option(|opt| matches!(opt, DhcpOption::LeaseTime(_)))
        {
            let requested_duration = Duration::from_secs(*requested_secs as u64);

            // Honor request if reasonable (not too short, not too long)
            let min_lease = Duration::from_secs(600); // 10 minutes minimum
            let max_lease = Duration::from_secs(86400 * 7); // 7 days maximum

            if requested_duration >= min_lease && requested_duration <= max_lease {
                return requested_duration;
            }
        }

        // Use global default
        self.config.lease_time
    }

    /// Determines server identifier (our IP address) for response.
    ///
    /// Selects appropriate server IP based on:
    /// - Relay address (giaddr) - use address on that network
    /// - Direct request - use address on client's network
    /// - Fallback - use first address in range
    ///
    /// Replaces C function `server_id()`.
    ///
    /// # Arguments
    ///
    /// * `context` - DHCP range context
    /// * `request` - Client request message
    ///
    /// # Returns
    ///
    /// IPv4 address to use as server identifier
    fn determine_server_id(&self, context: &DhcpRange, request: &DhcpMessage) -> Ipv4Addr {
        let giaddr = request.giaddr();

        // If request came through relay, use address on relay's network
        if !giaddr.is_unspecified() {
            // Stub: return giaddr itself (real implementation would find our IP on that network)
            return giaddr;
        }

        // Direct request: use address from context
        // Stub: use first address in range
        if let std::net::IpAddr::V4(server_ip) = context.start {
            return server_ip;
        }

        // Fallback: use broadcast address (should not happen)
        Ipv4Addr::new(255, 255, 255, 255)
    }

    /// Determines server identifier for REQUEST message processing.
    ///
    /// Similar to determine_server_id but specifically for REQUEST handling.
    fn determine_server_id_for_request(&self, _request: &DhcpMessage) -> Ipv4Addr {
        // Stub: return first available range's start address
        if let Some(range) = self.config.v4_ranges.first() {
            if let std::net::IpAddr::V4(server_ip) = range.start {
                return server_ip;
            }
        }

        Ipv4Addr::new(255, 255, 255, 255)
    }

    /// Finds static lease configuration for a MAC address.
    ///
    /// # Arguments
    ///
    /// * `mac` - Client hardware address
    ///
    /// # Returns
    ///
    /// Reference to static lease if configured, None otherwise
    fn find_static_lease(&self, mac: &MacAddress) -> Option<&StaticLease> {
        self.config.static_leases.iter().find(|lease| lease.mac == *mac)
    }

    /// Checks if an IP address is within a range.
    ///
    /// # Arguments
    ///
    /// * `ip` - IP address to check
    /// * `start` - Range start address
    /// * `end` - Range end address
    ///
    /// # Returns
    ///
    /// true if ip is within [start, end] inclusive
    fn ip_in_range(&self, ip: Ipv4Addr, start: Ipv4Addr, end: Ipv4Addr) -> bool {
        let ip_u32 = u32::from(ip);
        let start_u32 = u32::from(start);
        let end_u32 = u32::from(end);

        ip_u32 >= start_u32 && ip_u32 <= end_u32
    }

    /// Allocates an address from a DHCP range.
    ///
    /// Attempts to honor requested IP if present and available, otherwise
    /// finds first available address in range.
    ///
    /// # Arguments
    ///
    /// * `context` - DHCP range to allocate from
    /// * `request` - Client request message
    /// * `client_mac` - Client hardware address
    ///
    /// # Returns
    ///
    /// Ok(allocated IP address) or Err if no addresses available
    async fn allocate_address_from_range(
        &self,
        context: &DhcpRange,
        request: &DhcpMessage,
        client_mac: &MacAddress,
    ) -> Result<std::net::IpAddr, DhcpError> {
        // Check if client requested specific IP
        if let Some(DhcpOption::RequestedIpAddress(req_ip)) =
            request.get_option(|opt| matches!(opt, DhcpOption::RequestedIpAddress(_)))
        {
            // Verify requested IP is in range
            if let std::net::IpAddr::V4(start_ipv4) = context.start {
                if let std::net::IpAddr::V4(end_ipv4) = context.end {
                    if self.ip_in_range(*req_ip, start_ipv4, end_ipv4) {
                        // Check if IP is available
                        if self
                            .lease_manager
                            .find_by_ip(&std::net::IpAddr::V4(*req_ip))
                            .await
                            .is_none()
                        {
                            debug!(
                                client_mac = %client_mac,
                                requested_ip = %req_ip,
                                "Honoring requested IP address"
                            );
                            return Ok(std::net::IpAddr::V4(*req_ip));
                        }
                    }
                }
            }
        }

        // Find first available IP in range
        if let (std::net::IpAddr::V4(start_ipv4), std::net::IpAddr::V4(end_ipv4)) =
            (context.start, context.end)
        {
            let start_u32 = u32::from(start_ipv4);
            let end_u32 = u32::from(end_ipv4);

            for ip_u32 in start_u32..=end_u32 {
                let candidate_ip = Ipv4Addr::from(ip_u32);
                let candidate_addr = std::net::IpAddr::V4(candidate_ip);

                // Check if this IP is available
                if self.lease_manager.find_by_ip(&candidate_addr).await.is_none() {
                    debug!(
                        client_mac = %client_mac,
                        allocated_ip = %candidate_ip,
                        "Allocated new IP from range"
                    );
                    return Ok(candidate_addr);
                }
            }
        }

        // No addresses available
        Err(DhcpError::NoAddressAvailable {
            pool_name: format!("{}-{}", context.start, context.end),
        })
    }

    /// Handles DHCPREQUEST in SELECTING state.
    ///
    /// Client is accepting this server's offer.
    async fn handle_request_selecting(
        &self,
        request: &DhcpMessage,
        requested_ip: Ipv4Addr,
        server_id: Ipv4Addr,
    ) -> Result<DhcpMessage, DhcpError> {
        let client_mac = request.client_hardware_addr()?;

        // Verify requested IP is in our ranges
        let context = self.select_context(request).ok_or_else(|| {
            warn!(
                client_mac = %client_mac,
                requested_ip = %requested_ip,
                "No matching context for REQUEST"
            );
            DhcpError::NoAddressAvailable { pool_name: "no matching DHCP range".to_string() }
        })?;

        // Check if IP is available or already leased to this client
        if let Some(existing_lease) =
            self.lease_manager.find_by_ip(&std::net::IpAddr::V4(requested_ip)).await
        {
            // Verify it's leased to this client
            if existing_lease.mac != Some(client_mac) {
                warn!(
                    client_mac = %client_mac,
                    requested_ip = %requested_ip,
                    "IP already leased to different client"
                );
                return self.send_nak(request, "Address already allocated");
            }
        }

        // Allocate/renew the lease
        let lease_time = self.calculate_lease_time(context, request);
        let client_hostname =
            request.get_option(|opt| matches!(opt, DhcpOption::Hostname(_))).and_then(|opt| {
                if let DhcpOption::Hostname(hostname) = opt {
                    Some(hostname.clone())
                } else {
                    None
                }
            });

        match self
            .lease_manager
            .allocate_lease(
                std::net::IpAddr::V4(requested_ip),
                Some(client_mac),
                client_hostname,
                None,      // client_id not extracted yet
                "unknown", // interface not tracked yet
                lease_time,
            )
            .await
        {
            Ok(_lease) => {
                // Generate ACK
                let mut ack = DhcpMessage::new_reply(request);
                ack.set_yiaddr(requested_ip);

                let options = self.build_option_list(
                    context,
                    request,
                    requested_ip,
                    lease_time,
                    server_id,
                    MessageType::Ack,
                );

                for option in options {
                    ack.add_option(option);
                }

                info!(
                    client_mac = %client_mac,
                    acked_ip = %requested_ip,
                    lease_time_secs = lease_time.as_secs(),
                    "Generated DHCPACK (SELECTING)"
                );

                Ok(ack)
            }
            Err(e) => {
                error!(
                    client_mac = %client_mac,
                    requested_ip = %requested_ip,
                    error = %e,
                    "Failed to allocate lease"
                );
                self.send_nak(request, "Lease allocation failed")
            }
        }
    }

    /// Handles DHCPREQUEST in INIT-REBOOT state.
    ///
    /// Client is verifying cached address after reboot.
    async fn handle_request_init_reboot(
        &self,
        request: &DhcpMessage,
        requested_ip: Ipv4Addr,
    ) -> Result<DhcpMessage, DhcpError> {
        let client_mac = request.client_hardware_addr()?;

        // Verify requested IP is appropriate for client's network
        let context = self.select_context(request).ok_or_else(|| {
            warn!(
                client_mac = %client_mac,
                requested_ip = %requested_ip,
                "No matching context for INIT-REBOOT"
            );
            DhcpError::NoAddressAvailable { pool_name: "no matching DHCP range".to_string() }
        })?;

        // Check if IP is in range
        if let (std::net::IpAddr::V4(start), std::net::IpAddr::V4(end)) =
            (context.start, context.end)
        {
            if !self.ip_in_range(requested_ip, start, end) {
                warn!(
                    client_mac = %client_mac,
                    requested_ip = %requested_ip,
                    "Requested IP not in configured range"
                );
                return self.send_nak(request, "Wrong network");
            }
        }

        // Check if IP is available or leased to this client
        if let Some(existing_lease) =
            self.lease_manager.find_by_ip(&std::net::IpAddr::V4(requested_ip)).await
        {
            if existing_lease.mac != Some(client_mac) {
                warn!(
                    client_mac = %client_mac,
                    requested_ip = %requested_ip,
                    "IP leased to different client"
                );
                return self.send_nak(request, "Address in use");
            }
            // IP is leased to this client, renew it
        }

        // Allocate/renew lease and send ACK
        let lease_time = self.calculate_lease_time(context, request);
        let server_id = self.determine_server_id(context, request);

        match self
            .lease_manager
            .allocate_lease(
                std::net::IpAddr::V4(requested_ip),
                Some(client_mac),
                None,
                None,
                "unknown",
                lease_time,
            )
            .await
        {
            Ok(_) => {
                let mut ack = DhcpMessage::new_reply(request);
                ack.set_yiaddr(requested_ip);

                let options = self.build_option_list(
                    context,
                    request,
                    requested_ip,
                    lease_time,
                    server_id,
                    MessageType::Ack,
                );

                for option in options {
                    ack.add_option(option);
                }

                info!(
                    client_mac = %client_mac,
                    acked_ip = %requested_ip,
                    "Generated DHCPACK (INIT-REBOOT)"
                );

                Ok(ack)
            }
            Err(e) => {
                error!(
                    client_mac = %client_mac,
                    error = %e,
                    "Failed to allocate lease in INIT-REBOOT"
                );
                self.send_nak(request, "Lease allocation failed")
            }
        }
    }

    /// Handles DHCPREQUEST in RENEWING/REBINDING state.
    ///
    /// Client is extending existing lease.
    async fn handle_request_renewing(
        &self,
        request: &DhcpMessage,
        ciaddr: Ipv4Addr,
    ) -> Result<DhcpMessage, DhcpError> {
        let client_mac = request.client_hardware_addr()?;

        // Verify lease exists and belongs to this client
        let existing_lease =
            self.lease_manager.find_by_ip(&std::net::IpAddr::V4(ciaddr)).await.ok_or_else(
                || {
                    warn!(
                        client_mac = %client_mac,
                        ciaddr = %ciaddr,
                        "No lease found for RENEWING"
                    );
                    DhcpError::LeaseNotFound { ip: ciaddr.to_string() }
                },
            )?;

        if existing_lease.mac != Some(client_mac) {
            warn!(
                client_mac = %client_mac,
                ciaddr = %ciaddr,
                "Lease belongs to different client"
            );
            return self.send_nak(request, "Not your lease");
        }

        // Renew the lease
        let context = self.select_context(request).ok_or(DhcpError::NoAddressAvailable {
            pool_name: "no matching DHCP range".to_string(),
        })?;
        let lease_time = self.calculate_lease_time(context, request);
        let server_id = self.determine_server_id(context, request);

        match self.lease_manager.renew_lease(&std::net::IpAddr::V4(ciaddr), lease_time).await {
            Ok(_) => {
                let mut ack = DhcpMessage::new_reply(request);
                ack.set_yiaddr(ciaddr);

                let options = self.build_option_list(
                    context,
                    request,
                    ciaddr,
                    lease_time,
                    server_id,
                    MessageType::Ack,
                );

                for option in options {
                    ack.add_option(option);
                }

                info!(
                    client_mac = %client_mac,
                    renewed_ip = %ciaddr,
                    lease_time_secs = lease_time.as_secs(),
                    "Generated DHCPACK (RENEWING)"
                );

                Ok(ack)
            }
            Err(e) => {
                error!(
                    client_mac = %client_mac,
                    ciaddr = %ciaddr,
                    error = %e,
                    "Failed to renew lease"
                );
                self.send_nak(request, "Lease renewal failed")
            }
        }
    }

    /// Sends DHCPNAK response.
    ///
    /// # Arguments
    ///
    /// * `request` - Original request message
    /// * `message` - Human-readable error message
    ///
    /// # Returns
    ///
    /// DHCPNAK message
    fn send_nak(&self, request: &DhcpMessage, message: &str) -> Result<DhcpMessage, DhcpError> {
        let client_mac = request.client_hardware_addr()?;

        let mut nak = DhcpMessage::new_reply(request);
        nak.add_option(DhcpOption::MessageType(MessageType::Nak));
        nak.add_option(DhcpOption::Message(message.to_string()));

        warn!(
            client_mac = %client_mac,
            message = %message,
            "Sending DHCPNAK"
        );

        Ok(nak)
    }
}

// Additional context data structure extensions
// (In real implementation, these would be in config/types.rs)
impl DhcpRange {
    /// Gets the next-server IP for TFTP booting (stub)
    fn next_server(&self) -> Option<Ipv4Addr> {
        None // Stub: would be configured per range
    }
}

#[cfg(test)]
mod tests {
    // Unit tests would go here
    // - Test context selection logic
    // - Test lease time calculation
    // - Test option building
    // - Test message type handling
}
