// Copyright (c) 2000-2025 Simon Kelley
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; version 2 dated June, 1991, or
// (at your option) version 3 dated 29 June, 2007.

//! POSIX signal handling for dnsmasq
//!
//! This module provides async-safe signal handling using tokio's signal facilities.
//! It replaces the C implementation's direct signal(2) and sigaction(2) calls with
//! Rust's safe async signal handling.
//!
//! # Supported Signals
//!
//! - **SIGHUP**: Reload configuration, reopen log files, clear cache
//! - **SIGTERM**: Graceful shutdown with cleanup
//! - **SIGINT**: Graceful shutdown (same as SIGTERM)
//! - **SIGUSR1**: Dump cache contents to log
//! - **SIGUSR2**: Log statistics (cache hits, queries, DHCP leases)
//! - **SIGCHLD**: Reap terminated helper processes
//!
//! # Example
//!
//! ```no_run
//! use dnsmasq::platform::signals::{setup_signal_handlers, SignalEvent};
//! use tokio::sync::mpsc;
//!
//! # async fn example() -> Result<(), Box<dyn std::error::Error>> {
//! let (tx, mut rx) = mpsc::channel(16);
//! setup_signal_handlers(tx).await?;
//!
//! while let Some(signal) = rx.recv().await {
//!     match signal {
//!         SignalEvent::Reload => println!("Reloading configuration..."),
//!         SignalEvent::Shutdown => {
//!             println!("Shutting down gracefully...");
//!             break;
//!         }
//!         SignalEvent::DumpCache => println!("Dumping cache..."),
//!         SignalEvent::Statistics => println!("Logging statistics..."),
//!         SignalEvent::ChildExited(pid) => println!("Child {:?} exited", pid),
//!     }
//! }
//! # Ok(())
//! # }
//! ```

use crate::error::{DnsmasqError, PlatformError, Result};
use tokio::signal::unix::{signal, Signal, SignalKind};
use tokio::sync::mpsc;
use tracing::{debug, error, info, warn};

/// Events generated by signal handlers
///
/// These represent the different signals that dnsmasq handles and the
/// corresponding actions that should be taken.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SignalEvent {
    /// SIGHUP received - reload configuration
    ///
    /// Handler should:
    /// - Reload configuration file
    /// - Reopen log files
    /// - Clear DNS cache
    /// - Re-read /etc/hosts and other static data
    Reload,

    /// SIGTERM or SIGINT received - graceful shutdown
    ///
    /// Handler should:
    /// - Stop accepting new requests
    /// - Finish processing in-flight requests
    /// - Flush DHCP leases to disk
    /// - Close all sockets
    /// - Exit cleanly
    Shutdown,

    /// SIGUSR1 received - dump cache contents
    ///
    /// Handler should:
    /// - Log all entries in the DNS cache
    /// - Include TTLs and flags for each entry
    /// - Useful for debugging and monitoring
    DumpCache,

    /// SIGUSR2 received - log statistics
    ///
    /// Handler should:
    /// - Log DNS query statistics (total, cache hits, upstream)
    /// - Log DHCP lease statistics (total, active, expired)
    /// - Log DNSSEC validation statistics
    /// - Log memory usage
    Statistics,

    /// SIGCHLD received - child process exited
    ///
    /// Handler should:
    /// - Reap the zombie process with waitpid()
    /// - Log if the helper script failed
    /// - Clean up any resources associated with the child
    ///
    /// The parameter is the PID of the exited child, or None if unknown
    ChildExited(Option<i32>),
}

/// Handle for managing signal reception
///
/// This struct holds the tokio signal streams for all signals we handle.
/// It spawns an async task that monitors these streams and sends SignalEvents
/// to a channel when signals arrive.
pub struct SignalHandler {
    sighup: Signal,
    sigterm: Signal,
    sigint: Signal,
    sigusr1: Signal,
    sigusr2: Signal,
    sigchld: Signal,
}

impl SignalHandler {
    /// Create a new signal handler
    ///
    /// This registers signal handlers with the OS for all signals we care about.
    /// The handlers are async-signal-safe and will wake the tokio reactor when
    /// a signal arrives.
    ///
    /// # Errors
    ///
    /// Returns an error if any signal handler cannot be registered. This typically
    /// happens if:
    /// - Another signal handler is already installed
    /// - The process doesn't have permission to handle the signal
    /// - The signal number is invalid for the platform
    pub fn new() -> Result<Self> {
        Ok(Self {
            sighup: signal(SignalKind::hangup()).map_err(|e| {
                DnsmasqError::Platform(PlatformError::SignalHandler(format!(
                    "Failed to register SIGHUP handler: {}",
                    e
                )))
            })?,
            sigterm: signal(SignalKind::terminate()).map_err(|e| {
                DnsmasqError::Platform(PlatformError::SignalHandler(format!(
                    "Failed to register SIGTERM handler: {}",
                    e
                )))
            })?,
            sigint: signal(SignalKind::interrupt()).map_err(|e| {
                DnsmasqError::Platform(PlatformError::SignalHandler(format!(
                    "Failed to register SIGINT handler: {}",
                    e
                )))
            })?,
            sigusr1: signal(SignalKind::user_defined1()).map_err(|e| {
                DnsmasqError::Platform(PlatformError::SignalHandler(format!(
                    "Failed to register SIGUSR1 handler: {}",
                    e
                )))
            })?,
            sigusr2: signal(SignalKind::user_defined2()).map_err(|e| {
                DnsmasqError::Platform(PlatformError::SignalHandler(format!(
                    "Failed to register SIGUSR2 handler: {}",
                    e
                )))
            })?,
            sigchld: signal(SignalKind::child()).map_err(|e| {
                DnsmasqError::Platform(PlatformError::SignalHandler(format!(
                    "Failed to register SIGCHLD handler: {}",
                    e
                )))
            })?,
        })
    }

    /// Run the signal handling loop
    ///
    /// This async function waits for signals and sends corresponding SignalEvents
    /// to the provided channel. It runs until the channel is closed or an error
    /// occurs.
    ///
    /// # Arguments
    ///
    /// * `sender` - Channel to send SignalEvents to
    ///
    /// # Errors
    ///
    /// Returns an error if sending to the channel fails (channel closed).
    pub async fn run(mut self, sender: mpsc::Sender<SignalEvent>) -> Result<()> {
        loop {
            tokio::select! {
                _ = self.sighup.recv() => {
                    info!("Received SIGHUP - configuration reload requested");
                    if let Err(e) = sender.send(SignalEvent::Reload).await {
                        error!("Failed to send Reload event: {}", e);
                        return Err(DnsmasqError::Platform(PlatformError::SignalHandler(
                            "Signal event channel closed".to_string()
                        )));
                    }
                }

                _ = self.sigterm.recv() => {
                    info!("Received SIGTERM - initiating graceful shutdown");
                    if let Err(e) = sender.send(SignalEvent::Shutdown).await {
                        error!("Failed to send Shutdown event: {}", e);
                        return Err(DnsmasqError::Platform(PlatformError::SignalHandler(
                            "Signal event channel closed".to_string()
                        )));
                    }
                    // After shutdown signal, stop processing other signals
                    break;
                }

                _ = self.sigint.recv() => {
                    info!("Received SIGINT - initiating graceful shutdown");
                    if let Err(e) = sender.send(SignalEvent::Shutdown).await {
                        error!("Failed to send Shutdown event: {}", e);
                        return Err(DnsmasqError::Platform(PlatformError::SignalHandler(
                            "Signal event channel closed".to_string()
                        )));
                    }
                    // After shutdown signal, stop processing other signals
                    break;
                }

                _ = self.sigusr1.recv() => {
                    debug!("Received SIGUSR1 - cache dump requested");
                    if let Err(e) = sender.send(SignalEvent::DumpCache).await {
                        error!("Failed to send DumpCache event: {}", e);
                        return Err(DnsmasqError::Platform(PlatformError::SignalHandler(
                            "Signal event channel closed".to_string()
                        )));
                    }
                }

                _ = self.sigusr2.recv() => {
                    debug!("Received SIGUSR2 - statistics dump requested");
                    if let Err(e) = sender.send(SignalEvent::Statistics).await {
                        error!("Failed to send Statistics event: {}", e);
                        return Err(DnsmasqError::Platform(PlatformError::SignalHandler(
                            "Signal event channel closed".to_string()
                        )));
                    }
                }

                _ = self.sigchld.recv() => {
                    debug!("Received SIGCHLD - child process exited");
                    // Try to reap the child process and get its PID
                    let pid = reap_child_process();
                    if let Err(e) = sender.send(SignalEvent::ChildExited(pid)).await {
                        error!("Failed to send ChildExited event: {}", e);
                        return Err(DnsmasqError::Platform(PlatformError::SignalHandler(
                            "Signal event channel closed".to_string()
                        )));
                    }
                }
            }
        }

        Ok(())
    }
}

/// Reap a terminated child process
///
/// This function calls waitpid() to reap any zombie child processes. It's called
/// when SIGCHLD is received. Returns the PID of the reaped process, or None if
/// no process was available to reap.
///
/// # Implementation Note
///
/// This uses WNOHANG to avoid blocking if there's no child to reap. Multiple
/// children may exit before SIGCHLD is delivered, so this should be called in
/// a loop until it returns None.
fn reap_child_process() -> Option<i32> {
    use nix::sys::wait::{waitpid, WaitPidFlag, WaitStatus};
    use nix::unistd::Pid;

    match waitpid(Pid::from_raw(-1), Some(WaitPidFlag::WNOHANG)) {
        Ok(WaitStatus::Exited(pid, status)) => {
            if status == 0 {
                debug!("Child process {} exited successfully", pid);
            } else {
                warn!("Child process {} exited with status {}", pid, status);
            }
            Some(pid.as_raw())
        }
        Ok(WaitStatus::Signaled(pid, signal, _)) => {
            warn!("Child process {} terminated by signal {:?}", pid, signal);
            Some(pid.as_raw())
        }
        Ok(WaitStatus::StillAlive) => {
            // No child available to reap
            None
        }
        Ok(_) => {
            // Other wait statuses (stopped, continued) - ignore
            None
        }
        Err(nix::errno::Errno::ECHILD) => {
            // No child processes exist
            None
        }
        Err(e) => {
            error!("waitpid() failed: {}", e);
            None
        }
    }
}

/// Set up signal handlers and spawn the signal handling task
///
/// This is the main entry point for signal handling. It creates a SignalHandler,
/// spawns an async task to run the signal handling loop, and returns immediately.
///
/// # Arguments
///
/// * `sender` - Channel to send SignalEvents to. The caller should receive from
///   this channel and handle the events appropriately.
///
/// # Returns
///
/// Returns `Ok(())` if signal handlers were successfully registered and the
/// handling task was spawned. Returns an error if signal registration fails.
///
/// # Example
///
/// ```no_run
/// use dnsmasq::platform::signals::{setup_signal_handlers, SignalEvent};
/// use tokio::sync::mpsc;
///
/// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
/// let (tx, mut rx) = mpsc::channel(16);
/// setup_signal_handlers(tx).await?;
///
/// tokio::spawn(async move {
///     while let Some(signal) = rx.recv().await {
///         match signal {
///             SignalEvent::Reload => {
///                 // Reload configuration
///             }
///             SignalEvent::Shutdown => {
///                 // Initiate shutdown
///                 break;
///             }
///             SignalEvent::DumpCache => {
///                 // Dump cache
///             }
///             SignalEvent::Statistics => {
///                 // Log statistics
///             }
///             SignalEvent::ChildExited(pid) => {
///                 // Handle child exit
///             }
///         }
///     }
/// });
/// # Ok(())
/// # }
/// ```
pub async fn setup_signal_handlers(sender: mpsc::Sender<SignalEvent>) -> Result<()> {
    let handler = SignalHandler::new()?;

    // Spawn the signal handling task
    tokio::spawn(async move {
        if let Err(e) = handler.run(sender).await {
            error!("Signal handler task failed: {}", e);
        }
    });

    info!("Signal handlers installed for SIGHUP, SIGTERM, SIGINT, SIGUSR1, SIGUSR2, SIGCHLD");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_signal_handler_creation() {
        // Should be able to create a signal handler
        let result = SignalHandler::new();
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_setup_signal_handlers() {
        let (tx, _rx) = mpsc::channel(16);
        let result = setup_signal_handlers(tx).await;
        assert!(result.is_ok());
    }

    #[test]
    fn test_signal_event_equality() {
        assert_eq!(SignalEvent::Reload, SignalEvent::Reload);
        assert_eq!(SignalEvent::Shutdown, SignalEvent::Shutdown);
        assert_ne!(SignalEvent::Reload, SignalEvent::Shutdown);
        assert_eq!(SignalEvent::ChildExited(Some(123)), SignalEvent::ChildExited(Some(123)));
        assert_ne!(SignalEvent::ChildExited(Some(123)), SignalEvent::ChildExited(Some(456)));
    }
}
